version: "3"
services:
    pg-tasks:
        container_name: pg-tasks
        image: postgres:9.6
        ports:
          - 5433:5432
        environment:
          - POSTGRES_DB=tasks
          - POSTGRES_PASSWORD=password
    
    backend_tst:
        container_name: backend-tst
        image: back_tst:build_${BUILD_NUMBER}
        build:
            context: .
            args:
                - WAR_FILE=tasks-backend/target/tasks-backend.war
                - CONTEXT_NAME=tasks-backend
        ports:
            - 8001:8080
        environment:
            - DATABASE_HOST=db
            - DATABASE_PORT=5432
            - DATABASE_USER=postgres
            - DATABASE_PASSWD=passwd
            #- DATABASE_UPDATE=none
        depends_on:
            - pg-tasks