version: "3"
services:
    pg-tasks:
        container_name: pg-tasks
        image: postgres:9.6
        ports:
          - 5433:5432
        environment:
          - POSTGRES_DB=tasks
          - POSTGRES_PASSWORD=password
    
    backend:
        container_name: backend-tst
        image: back_tst:build_${BUILD_NUMBER}
        build:
            context: .
            args:
                - WAR_FILE=tasks-backend/target/tasks-backend.war
                - CONTEXT_NAME=tasks-backend
        ports:
            - 9554:8080
        environment:
            - DATABASE_HOST=pg-tasks
            - DATABASE_PORT=5432
            - DATABASE_USER=postgres
            - DATABASE_PASSWD=password
            #- DATABASE_UPDATE=none
        depends_on:
            - pg-tasks
            
     frontend:
        container_name: frontend-tst
        image: front_tst:build_${BUILD_NUMBER}
        build:
            context: .
            args:
                - WAR_FILE=tasks-frontend/target/tasks.war
                - CONTEXT_NAME=tasks
        ports:
            - 9555:8080
        environment:
            - BACKEND_HOST=backend
            - BACKEND_PORT=8080
            - APP_VERSION=build_${BUILD_NUMBER}
        #depends_on:
        #  - backend
             
    selenium-hub:
        image: selenium/hub:3.141.59-zinc
        container_name: selenium-hub
        networks:
            - seleniumGrid
        ports:
            - "4444:4444"

    chrome:
        image: selenium/node-chrome:3.141.59-zinc
        container_name: Chrome-1
        networks:
            - seleniumGrid
        depends_on:
            - selenium-hub
        environment:
            - HUB_HOST=selenium-hub
            - HUB_PORT=4444
            - NODE_MAX_INSTANCES=2
            - NODE_MAX_SESSIONS=2
            
    chrome2:
        image: selenium/node-chrome:3.141.59-zinc
        container_name: Chrome-2
        networks:
            - seleniumGrid
        depends_on:
            - selenium-hub
        environment:
            - HUB_HOST=selenium-hub
            - HUB_PORT=4444
            - NODE_MAX_INSTANCES=2
            - NODE_MAX_SESSIONS=2

networks:
  seleniumGrid:
