version: "3"
services:   
    frontend:
        container_name: frontend-tst
        image: front_tst:build_${BUILD_NUMBER}
        build:
            context: .
            args:
                - WAR_FILE=tasks-frontend/target/tasks.war
                - CONTEXT_NAME=tasks
        ports:
            - 9555:8080
        environment:
            - BACKEND_HOST=backend
            - BACKEND_PORT=8080
            - APP_VERSION=build_${BUILD_NUMBER}
        #depends_on:
        #  - backend